### PR TITLE
[#222, #223, #229] Hero and Logo Wall Blocks

### PR DESCRIPTION
**Pull request by snowiewdev**
## Description

New blocks to accommodate redesign in homepage, reference to issue in #222 #223 

Hero Block - Test URLs:
- Before: https://main--helix-website--adobe.hlx.page/drafts/redesign/new-home
- After: https://redesign-hero-and-logo-wall--helix-website--adobe.hlx.page/drafts/redesign/blocks/hero

Logo Wall Block - Test URLs:
- Before: https://main--helix-website--adobe.hlx.page/drafts/redesign/new-home
- After: https://redesign-hero-and-logo-wall--helix-website--adobe.hlx.page/drafts/redesign/blocks/logo-wall

Documentation:
- [Hero Block Readme](https://github.com/adobe/helix-website/tree/redesign/hero-and-logo-wall/blocks/hero)
- [Logo Wall Block Readme](https://github.com/adobe/helix-website/tree/redesign/hero-and-logo-wall/blocks/logo-wall)

### CODE REVIEW

**Review by nicolerego — APPROVED** [review]

**Review by solomon71 — APPROVED** [review]

**Comment by solomon71** [comment]
@snowiewdev - see what we can do about the CLS for the logo-wall

**Comment by solomon71** [comment]
^ see https://github.com/solomon71/tbx-olympus/blob/main/styles/styles.css#LL135C1-L141C2 for font fallback for lazy-load of the web-font. @snowiewdev

**Comment by snowiewdev** [comment]
@nicolerego @solomon71 just added support for Hero block to transform as #229 Documentation Hero, please take a look, thank you! 

@solomon71 thanks for the feedback. I saw there's font fallback for 'adobe-clean' in `font.css` [here](https://github.com/adobe/helix-website/blob/redesign/hero-and-logo-wall/fonts/fonts.css) and font-face for 'Trebuchet MS' in top of`styles.css`. Should I move the `fonts.css` into `lazy-styles.css` like [this]( https://github.com/solomon71/tbx-olympus/blob/main/styles/lazy-styles.css) or add another font fallback before 'Trebuchet MS' with local src as 'Trebuchet MS'? thank you.

**Review by nicolerego — APPROVED** [review]

**Comment by solomon71** [comment]
> @nicolerego @solomon71 just added support for Hero block to transform as #229 Documentation Hero, please take a look, thank you!
> 
> @solomon71 thanks for the feedback. I saw there's font fallback for 'adobe-clean' in `font.css` [here](https://github.com/adobe/helix-website/blob/redesign/hero-and-logo-wall/fonts/fonts.css) and font-face for 'Trebuchet MS' in top of`styles.css`. Should I move the `fonts.css` into `lazy-styles.css` like [this](https://github.com/solomon71/tbx-olympus/blob/main/styles/lazy-styles.css) or add another font fallback before 'Trebuchet MS' with local src as 'Trebuchet MS'? thank you.

@snowiewdev 
Yes, let's try moving the font refs to lazy-styles.css first. There is a  conflict in styles.css, can you look at that too?

**Pull request merged**
