### PR TITLE
feat: questionnaire block

### PR DESCRIPTION
**Pull request by fkakatie**
## Description

Specific-use questionnaire block.

## How Has This Been Tested?

https://cdn-q--helix-website--adobe.aem.page/drafts/fkakatie/cdn-questionnaire

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by trieloff** [comment]
Thanks for the first draft, here are assorted comments:
- we'll have questionnaires that are not just about CDN, so we probably need a prefix that is not `cdn-` for the class names
- on the math
  - I first thought that we just need linear scoring, i.e. if the weight is `1`, then strong agreement increases the overall score for that option by `1` and strong disagreement decreases by `1`
  - This would also work in the reverse, so a `weight` of `-1` for the question "I am vegetarian" would be correct for all meat-based food options
  - But I think we also need a way to express that we want to increase the score if the question is answered affirmative, but don't do anything if not. I've been thinking of using `+1` for that
  - For now I hope that we don't need the inverse, because we can change the questions accordingly
 - To present the conclusions, I've been thinking of having one row for each possible result: the first column would be the same title as in the spreadsheet and the second column would contain text and image – and probably a link to setting up the choice that we suggest

**Comment by fkakatie** [comment]
> Thanks for the first draft, here are assorted comments:
> 
> * we'll have questionnaires that are not just about CDN, so we probably need a prefix that is not `cdn-` for the class names

I am pathologically bad at naming. Changed.

> * on the math
>   
>   * I first thought that we just need linear scoring, i.e. if the weight is `1`, then strong agreement increases the overall score for that option by `1` and strong disagreement decreases by `1`
>   * This would also work in the reverse, so a `weight` of `-1` for the question "I am vegetarian" would be correct for all meat-based food options

I *think* this has been implemented correctly. Please double-check my math.

>   * But I think we also need a way to express that we want to increase the score if the question is answered affirmative, but don't do anything if not. I've been thinking of using `+1` for that
>   * For now I hope that we don't need the inverse, because we can change the questions accordingly

This exceeds my understanding. Think this needs to be handled in both `buildQuestion` and `calculateResults`.

> * To present the conclusions, I've been thinking of having one row for each possible result: the first column would be the same title as in the spreadsheet and the second column would contain text and image – and probably a link to setting up the choice that we suggest

I did something wildly different. See the accordion structure, let me know.

**Comment by rrusher** [comment]
@fkakatie The math is correct.
@trieloff In order to keep as simple addition and multiplication, I would set the weights for each product as a number, as opposed to "++1". If it's important, make it greater than 1.

**Comment by trieloff** [comment]
I would not worry about any of the hardcoded stuff for now. If we need flexibility later, we add it later.

**Pull request merged**
