### PR TITLE
Blog-template design

### PR DESCRIPTION
**Pull request by asthabh23**
## Description

This PR consists of design for blog-template layout.

## Related Issue

This is a new feature or section to be introduced in helix website

## Motivation and Context

This is the start point to setup the base layout for public facing blogs around Edge Delivery Services. The blog template can be used to create blogs that will cover details around the specific topics of Edge Delivery Services, related screenshots (as required) along with the author details who would be creating the blog.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

https://main--helix-website--adobe.aem.page/drafts/asthabharga/blog
vs
https://blog-template--helix-website--adobe.aem.page/drafts/asthabharga/blog

This PR addresses issue #458

### CODE REVIEW

**Review by trieloff — COMMENTED** [review]
Additional things to change:
- hide the back button, it currently still appears
- let's try to reformat the date in the author box to read January 29th, 2024 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat can help with that

**Comment by asthabh23** [comment]
> Additional things to change:
> 
> * hide the back button, it currently still appears
> * let's try to reformat the date in the author box to read January 29th, 2024 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat can help with that

@trieloff , for the back button, I left it as is since we have to link it to main blog page too.. shall I still remove it for the time being?
Regarding date, I will update the logic 👍🏻, unable to proceed at the moment due to the hlx cli issue as it is unable to sync with this branch.

**Comment by bdelacretaz** [comment]
I initially didn't find the https://github.com/asthabh23 link which is behind the GitHub logo. To me that logo implies a link to GitHub itself, I didn't expect it to link to the author's page.

How about linking from the author's picture and name instead? That would be more obvious to me.

I also suggest adding an `alt` attribute to the author's picture, with the author name.

**Comment by asthabh23** [comment]
> I initially didn't find the https://github.com/asthabh23 link which is behind the GitHub logo. To me that logo implies a link to GitHub itself, I didn't expect it to link to the author's page.
> 
> How about linking from the author's picture and name instead? That would be more obvious to me.
> 
> I also suggest adding an `alt` attribute to the author's picture, with the author name.

Thanks @bdelacretaz for your inputs! I have added author name to author's picture.

Regarding Github profile for author, we have the logo explicitly, adding link to the image or name might not be intuitive...
@trieloff wdyt?

**Review by trieloff — APPROVED** [review]

**Pull request merged**
