### PR TITLE
fix(rum-oversight): unknown filter should return empty set

### PR DESCRIPTION
**Pull request by kptdobe**
https://github.com/adobe/helix-website/pull/663 "backport to oversight"

### CODE REVIEW

**Review by trieloff — APPROVED** [review]

**Comment by trieloff** [comment]
@karlpauls we should add this to distiller.

**Comment by trieloff** [comment]
And then close it in favor of #669

**Review by karlpauls — CHANGES_REQUESTED** [review]
This seems to fail the tests: 

```test at test/cruncher.test.js:712:3
✖ DataChunk.filter(userAgent) negation (0.836417ms)
  AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
  
  0 !== 1
  
      at TestContext.<anonymous> ( ) {
    generatedMessage: true,
    code: 'ERR_ASSERTION',
    actual: 0,
    expected: 1,
    operator: 'strictEqual'
  }
```

Otherwise, it seems to apply cleanly to the distiller so if I can get the test to pass I'll follow the suggestion from @trieloff.

**Comment by karlpauls** [comment]
I think I see the issue, the test for the negation has a filter for the host facet that is not defined. I fixed it like this:

```--- a/tools/oversight/test/cruncher.test.js
+++ b/tools/oversight/test/cruncher.test.js
@@ -776,6 +776,7 @@ describe('DataChunks', () => {
     d.load(chunks1);
 
     // define facet functions
+    d.addFacet('host', (bundle) => bundle.host);
     d.addFacet(
       // as a convention, we use ! to indicate negation. When used in URL parameters, this
       // looks like a nice filter:  ?userAgent!=desktop
```

in https://github.com/adobe/rum-distiller/pull/9 - @kptdobe, does that make sense and if so, should I merge it in rum-distiller and close this issue in favor of #669 as suggested by @trieloff?

**Comment by kptdobe** [comment]
If we plan to use the distiller in oversight, yes, we can close this one.

**Pull request closed without merging**
